[[plugins]] #Linter
build = 'pip install flake8 isort'
repo = 'w0rp/ale'
on_path = '.*'

[[plugins]] # TOMLのシンタックスハイライト
repo  = 'cespare/vim-toml'
on_ft = 'toml'

[[plugins]] # ステータス行を見やすく
repo = 'itchyny/lightline.vim'
