[[plugins]]
repo = 'Shougo/defx.nvim'

[[plugins]]
repo = 'simeji/winresizer'

[[plugins]]
repo = 'autozimu/LanguageClient-neovim'
rev = 'next'
build = 'bash install.sh'
# プラグインのアップデート時に呼び出されるコールバック
hook_post_update = 'call hook#post_update#language_client_neovim#load()'
# プラグインが読み込まれる際に呼び出されるコールバック
hook_add         = 'source ~/.config/nvim/rc/LanguageClient-neovim.vim'

[[plugins]]
repo = 'Shougo/context_filetype.vim'

[[plugins]]
repo = 'Shougo/deoplete.nvim'
depends = 'context_filetype.vim'
on_event = 'InsertEnter'
hook_source = 'source ~/.config/nvim/rc/deoplete.vim'

[[plugins]]
repo = 'junegunn/fzf'
build = './install -all'

[[plugins]]
repo = 'junegunn/fzf.vim'

[[plugins]]
repo = "tpope/vim-fugitive"
